blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView

urlpatterns = [
    path('', PostListView.as_view()),
    path('<slug:slug>/', PostDetailView.as_view(), name='post_detail'),
]

engclub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('homepage.urls')),
    path('blog/', include('blog.urls')),
    path('staff/', include('staff.urls')),
    path('courses/', include('courses.urls')),
    path('about/', include('about.urls')),
    path('admin/', admin.site.urls),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from ckeditor.fields import RichTextField
from hitcount.models import HitCountMixin, HitCount

# Create your models here.

STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Post(models.Model, HitCountMixin):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now=True)
    content =  RichTextField()
    content_preview = models.CharField(max_length=200)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    title_image = models.ImageField(upload_to='blog')
    
    hit_count_generic = GenericRelation(
        HitCount, object_id_field='object_pk',
        related_query_name='hit_count_generic_relation')

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView
from hitcount.views import HitCountDetailView
from .models import Post


class PostListView(ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'blog.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Blog'
        return context


class PostDetailView(HitCountDetailView):
    model = Post
    template_name = 'post_detail.html'
    count_hit = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Blog'
        context['popular_posts'] = Post.objects.order_by('hit_count_generic')[:5]
        return context

blog/templates/blog.html
{% extends 'base.html' %}
{% load hitcount_tags %}

{% block content %}
    
    <section class="hero-wrap hero-wrap-2" style="background-image: url('/media/bg_1.jpg');">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
            <h1 class="mb-2 bread">Blog</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="/">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Teacher <i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>

		
		<section class="ftco-section bg-light">
			<div class="container">
				<div class="row">
          
          {% for post in post_list %}          
            <div class="col-md-6 col-lg-4 ftco-animate">
              <div class="blog-entry">
                <a href="blog-single.html" class="block-20 d-flex align-items-end" style="background-image: url({{ post.title_image.url }});">
                  <div class="meta-date text-center p-2">
                    <span class="day">{{ post.created_on|date:'d' }}</span>
                    <span class="mos">{{ post.created_on|date:'M' }}</span>
                    <span class="yr">{{ post.created_on|date:'Y' }}</span>
                  </div>
                </a>
                <div class="text bg-white p-4">
                  <h3 class="heading"><a href="{% url 'post_detail' post.slug  %}">{{ post.title }}</a></h3>
                  <p>{{ post.content_preview }}</p>
                  <div class="d-flex align-items-center mt-4">
                    <p class="mb-0"><a href="{% url 'post_detail' post.slug  %}" class="btn btn-primary">Read More <span class="ion-ios-arrow-round-forward"></span></a></p>
                    <p class="ml-auto mb-0">
                      <span class="mr-2">{{ post.author.first_name }} {{ post.author.last_name }}</span>
                      <span class="icon-eye"></span> {% get_hit_count for post %}
                    </p>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}         
          
          </div>
        </div>
			</div>
		</section>
		
{% endblock %}

blog/templates/post_detail.html
{% extends 'base.html' %}
{% load hitcount_tags %}
{% block content %}
    
    <section class="hero-wrap hero-wrap-2" style="background-image: url({{ object.title_image.url }});">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
            <h1 class="mb-2 bread">{{ object.title }}</h1>
             <p class="breadcrumbs"><span class="mr-2"><a href="/">Home <i class="ion-ios-arrow-forward"></i></a></span> <span class="mr-2"><a href="/blog/">Blog <i class="ion-ios-arrow-forward"></i></a></span> <span> {{ object.title }} <i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>

		
		<section class="ftco-section">
			<div class="container">
				<div class="row">
          <div class="col-lg-8 ftco-animate">
            {{ object.content|safe }}
            <div class="about-author d-flex p-4 bg-light">
              <div class="bio mr-5">
                <img src="{{ object.author.userprofile.avatar.url }}" alt="Image placeholder" class="img-fluid mb-4">
              </div>
              <div class="desc">
                <h3>{{ object.author.first_name }} {{ object.author.last_name }} {{ number }}</h3>
                {{ object.author.userprofile.bio }}
              </div>
            </div>


          </div> <!-- .col-md-8 -->

          <div class="col-lg-4 sidebar ftco-animate">
            
            <div class="sidebar-box ftco-animate">
              <h3>Popular Articles</h3>

              {% for post in popular_posts %}
                <div class="block-21 mb-4 d-flex">
                  <a class="blog-img mr-4" style="background-image: url({{ post.title_image.url }});"></a>
                  <div class="text">
                    <h3 class="heading"><a href="{% url 'post_detail' post.slug  %}">{{ post.title }}</a></h3>
                    <div class="meta">
                      <div><a href="#"><span class="icon-calendar"></span> {{ post.created_on|date:'M d, Y' }}</a></div>
                      <div><a href="#"><span class="icon-person"></span>{{ post.author.first_name }} {{ post.author.last_name }}</a></div>
                      <div><a href="#"><span class="icon-eye"></span> {% get_hit_count for post %}</a></div>
                    </div>
                  </div>
                </div>
              {% endfor %}

          </div><!-- END COL -->
        </div>
			</div>
		</section>
		
{% endblock %}